stages:
  fetch_raw:
    cmd: data/fetch_raw.sh data/leagues.json data/raw/clubs.json data/raw/players.json data/raw/appearances.json
    outs:
    - data/raw/clubs.json
    - data/raw/players.json
    - data/raw/appearances.json
  data_prep:
    cmd: (cd prep && python prep.py ../data/raw && mv stage/* ../data/prep)
    deps:
    - data/raw/appearances.json
    - data/raw/clubs.json
    outs:
    - data/prep/appearances.csv
    - data/prep/clubs.csv
