name: Player Scores Data Pipeline

on:
  push:
    branches: [ data-pipeline ]
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  data-pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Run data pipeline
      run: |
        ls
        ls /home/runner/work/player-scores/player-scores/data
        ls /home/runner/work/player-scores/player-scores
        echo "$PWD"
        dvc repro
