name: Player Scores Data Pipeline

on:
  push:
    branches: [ data-pipeline ]
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  data-pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: iterative/setup-dvc@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: player-scores
    - run: |
        conda info
        conda list
    - name: Run data pipeline
      run: |
        conda activate player-scores
        dvc repro
