name: Player Scores Data Pipeline

on:
  push:
   branches:
     - build-on-push
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  data-pipeline:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - run: echo "${{ github.event.head_commit.message or 'Automatic update from github actions'}}"
    # - uses: actions/checkout@v2
    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     environment-file: environment.yml
    #     activate-environment: player-scores
    # - name: Run pipeline
    #   run: |
    #     python -m ipykernel install --user --name player-scores
    #     dvc repro
    # - name: Update kaggle dataset
    #   env:
    #     KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
    #     KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
    #   run: |
    #     python data/prep/dataset-metadata.py
    #     echo "${{ github.event.head_commit.message or 'Automatic update from github actions'}}"
    #     kaggle datasets version -p data/prep -m "${{ github.event.head_commit.message or 'Automatic update from github actions'}}" -d
